package com.bluntsoftware.karateschool.modules.karateschool.repository;

import com.bluntsoftware.karateschool.modules.karateschool.domain.Criteria;
import com.genx.framework.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Criteria.
* @author autogenerated
*/

@Repository("karateschoolCriteriaRepository")
@Qualifier("karateschool")
//@RepositoryRestResource(collectionResourceRel="karateschool.Criteria", path="karateschool/Criteria")
public interface CriteriaRepository extends GenericRepository<Criteria,Integer>  {

}