package com.bluntsoftware.karateschool.modules.karateschool.repository;

import com.bluntsoftware.karateschool.modules.karateschool.domain.Rcriteria;
import com.genx.framework.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Rcriteria.
* @author autogenerated
*/

@Repository("karateschoolRcriteriaRepository")
@Qualifier("karateschool")
//@RepositoryRestResource(collectionResourceRel="karateschool.Rcriteria", path="karateschool/Rcriteria")
public interface RcriteriaRepository extends GenericRepository<Rcriteria,Integer>  {

}