package com.bluntsoftware.karateschool.modules.karateschool.repository;

import com.bluntsoftware.karateschool.modules.karateschool.domain.School;
import com.genx.framework.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: School.
* @author autogenerated
*/

@Repository("karateschoolSchoolRepository")
@Qualifier("karateschool")
//@RepositoryRestResource(collectionResourceRel="karateschool.School", path="karateschool/School")
public interface SchoolRepository extends GenericRepository<School,Integer>  {

}