package com.bluntsoftware.karateschool.modules.karateschool.repository;

import com.bluntsoftware.karateschool.modules.karateschool.domain.Studentrank;
import com.genx.framework.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Studentrank.
* @author autogenerated
*/

@Repository("karateschoolStudentrankRepository")
@Qualifier("karateschool")
//@RepositoryRestResource(collectionResourceRel="karateschool.Studentrank", path="karateschool/Studentrank")
public interface StudentrankRepository extends GenericRepository<Studentrank,Integer>  {

}